/**
 * Regenerates supabase/update-content.sql from the bundled defaults in
 * src/data/portfolioData.ts.
 *
 * The database is the source of truth at runtime, so this is the one-way door
 * that pushes code-side content edits live: run this, then paste the SQL into
 * Supabase -> SQL Editor -> Run. Without it the two drift apart and the
 * deployed site can end up serving content that contradicts the repo.
 *
 *   npm run gen:content
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
// Imported from the data module rather than PortfolioDataContext: the context
// pulls in supabaseClient, which reads import.meta.env and is Vite-only.
import {
  DEFAULT_PERSONAL_INFO,
  DEFAULT_ABOUT_DATA,
  PROJECTS,
  SKILLS,
  TIMELINE,
  TESTIMONIALS,
  FREQUENT_QUESTIONS,
} from '../src/data/portfolioData';
import type { PortfolioContent } from '../src/types';

const DEFAULT_CONTENT: PortfolioContent = {
  personalInfo: DEFAULT_PERSONAL_INFO,
  about: DEFAULT_ABOUT_DATA,
  projects: PROJECTS,
  skills: SKILLS,
  timeline: TIMELINE,
  testimonials: TESTIMONIALS,
  faqs: FREQUENT_QUESTIONS,
};

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'supabase', 'update-content.sql');

const json = JSON.stringify(DEFAULT_CONTENT);

// The payload is wrapped in a $rp$ dollar-quoted string so quotes and backslashes
// inside the content need no escaping. Bail out rather than emit broken SQL.
if (json.includes('$rp$')) {
  throw new Error('Content contains the $rp$ dollar-quote delimiter; pick another tag.');
}

const sql = `-- =====================================================================
--  UPDATE PORTFOLIO CONTENT
--  Generated by scripts/generate-content-sql.ts - do not edit by hand.
--  Regenerate with:  npm run gen:content
--
--  Run in: Supabase Dashboard -> SQL Editor -> New query -> Run
--
--  WARNING: this REPLACES the live content with the snapshot in
--  src/data/portfolioData.ts. Anything edited in the owner editor since that
--  snapshot was taken is overwritten. The backup step below runs first and
--  keeps a timestamped copy, so a bad run can always be undone.
-- =====================================================================

-- 1. Back up whatever is live right now.
create table if not exists public.portfolio_content_backup (
  backed_up_at timestamptz not null default now(),
  content      jsonb       not null
);
insert into public.portfolio_content_backup (content)
select content from public.portfolio_content where id = 1;

-- 2. Write the new content.
insert into public.portfolio_content (id, content)
values (1, $rp$${json}$rp$::jsonb)
on conflict (id) do update set content = excluded.content;

-- 3. Verify.
select
  content->'personalInfo'->>'name'            as name,
  content->'personalInfo'->>'role'            as role,
  content->'personalInfo'->>'email'           as email,
  jsonb_array_length(content->'projects')     as projects,
  jsonb_array_length(content->'timeline')     as timeline,
  jsonb_array_length(content->'testimonials') as references_,
  (select count(*) from jsonb_array_elements(content->'projects') p
     where (p->>'featured')::boolean)                              as featured_on_cv,
  (select count(*) from jsonb_array_elements(content->'testimonials') r
     where r->>'phone' is not null and r->>'phone' <> '')          as refs_with_phone,
  updated_at
from public.portfolio_content where id = 1;

-- To roll back to the previous version:
--   update public.portfolio_content set content = (
--     select content from public.portfolio_content_backup
--     order by backed_up_at desc limit 1
--   ) where id = 1;
`;

writeFileSync(outPath, sql, 'utf8');
console.log(
  `wrote ${outPath}\n` +
    `  projects:   ${DEFAULT_CONTENT.projects.length} (${DEFAULT_CONTENT.projects.filter(p => p.featured).length} featured)\n` +
    `  timeline:   ${DEFAULT_CONTENT.timeline.length}\n` +
    `  references: ${DEFAULT_CONTENT.testimonials.length}\n` +
    `  payload:    ${(json.length / 1024).toFixed(1)} KB`
);
